### ISSUE TITLE
Periodical mailings tests failing

### ISSUE THREAD

**Issue by ssoulless** [Sology/maily_herald#13]
Hi, today I pulled from your master and ran tests, this one is failing, Travis should show the build failing:
```
Failed examples:

rspec ./spec/models/maily_herald/periodical_mailing_spec.rb:116 # MailyHerald::PeriodicalMailing Periodical Delivery should deliver mailings periodically
```

Test was passing before d904758d61f97fbbaf973e733acf5f3165cb7fbe

**Comment by ardahaal** [comment]
@ssoulless All tests passes on master branch now. Could You check once again on Your app and get back to me?

**Comment by ssoulless** [comment]
Done everything is passing now
