### ISSUE TITLE
debugger gem doesn't work with Ruby 2.1+

### ISSUE THREAD

**Issue by ssoulless** [Sology/maily_herald#8]
I was doing some development on this gem, I updated my Ruby version to 2.1.4 and after update gems I see that Debugger gem is no longer compatible with newer ruby versions, I suggest use byebug instead.

**Comment by ljachymczyk** [comment]
Hi, thanks for noticing. Maily is technically compatible with Rails 3.2 too so I guess the best option would be to just remove debugging from Gemfile completely.
