### ISSUE TITLE
Running tests

### ISSUE THREAD

**Issue by ssoulless** [Sology/maily_herald#9]
Im trying to run tests, however when I try to set up the database
```
rake db:setup
```
Rake is aborted and I get the following message:
ActiveRecord::RecordInvalid: Validation failed: List can't be blank, List can't be blank

If you provide some instructions for running tests that would be great.

**Comment by ljachymczyk** [comment]
Will look at this and provide some testing/contributing instructions in the readme.

**Comment by ljachymczyk** [comment]
`rake db:setup` should work fine now. Also added information about contributing and testing to README.
